Repository sean0x42/kauri, pull requests merged in 2019-09, with the labels that each got.

#105 Server updates to comply with the current KDF spec
  server/src/document/node.rs
  server/src/parsers/odt/text.rs
Labels: size/M

#107 ODT line and page break parsing support
  server/src/parsers/odt/text.rs
Labels: size/M

#108 Bump Preact to 10.0.0-rc.3 (X Release Candidate 3)
  client/package.json
  client/yarn.lock
Labels: client, dependencies, size/S

#109 Add and configure Typescript
  client/jest.config.js
  client/package.json
  client/postcss.config.js
  client/src/renderer/helpers/inflections.test.ts
  client/src/renderer/helpers/inflections.ts
  client/src/renderer/redux/reducers/document.js
  client/tsconfig.json
  client/webpack.renderer.additions.js
  client/yarn.lock
Labels: client, javascript, meta, size/L

#104 Wrap document content into pages
  client/jest.config.js
  client/src/renderer/components/Editor/Elements/Heading.jsx
  client/src/renderer/components/Editor/Elements/List.jsx
  client/src/renderer/components/Editor/Elements/index.jsx
  client/src/renderer/components/Editor/Nodes/index.jsx
  client/src/renderer/components/Editor/Nodes/styles.scss
  client/src/renderer/components/Editor/Page/index.jsx
  client/src/renderer/components/Editor/Page/styles.scss
  client/src/renderer/components/Editor/index.jsx
  client/src/renderer/components/Editor/styles.scss
  client/src/renderer/dom/RenderError.js
  client/src/renderer/dom/render.jsx
  client/src/renderer/helpers/units.test.ts
  client/src/renderer/helpers/units.ts
  client/src/renderer/redux/actions/cache.test.ts
  client/src/renderer/redux/actions/cache.ts
  client/src/renderer/redux/actions/index.js
  client/src/renderer/redux/actions/types.ts
  client/src/renderer/redux/reducers/cache.js
  client/src/renderer/redux/reducers/cache.test.js
  client/src/renderer/redux/reducers/index.js
  client/src/renderer/render/content.tsx
  client/src/renderer/render/index.ts
  client/src/renderer/render/style.ts
  client/src/renderer/styles/elements/_body.scss
Labels: size/XL

#110 Add styles reducer
  client/src/renderer/redux/actions/index.js
  client/src/renderer/redux/actions/pageStyles.js
  client/src/renderer/redux/actions/pageStyles.test.js
  client/src/renderer/redux/actions/styles.js
  client/src/renderer/redux/actions/styles.test.js
  client/src/renderer/redux/actions/types.ts
  client/src/renderer/redux/reducers/index.js
  client/src/renderer/redux/reducers/pageStyles.js
  client/src/renderer/redux/reducers/pageStyles.test.js
  client/src/renderer/redux/reducers/styles.js
  client/src/renderer/redux/reducers/styles.json
  client/src/renderer/redux/reducers/styles.test.js
Labels: size/L

#112 Fixed fetching from server
  client/src/renderer/components/Application/index.jsx
  client/src/renderer/helpers/menu.js
  client/src/renderer/redux/actions/document.js
  server/src/controllers/load.rs
  server/src/controllers/util.rs
  server/src/main.rs
Labels: size/M

#111 Feature keyboard shortcut
  client/src/renderer/commands/index.js
  client/src/renderer/commands/keybinds.json
  client/src/renderer/commands/shortcuts.js
  client/src/renderer/commands/shortcuts.test.js
  client/src/renderer/components/App/index.jsx
  client/src/renderer/components/Clipboard/index.jsx
  client/src/renderer/components/ShortcutListener.js
  client/src/renderer/helpers/uniqueIdGen.js
  client/src/renderer/redux/actions/commands.js
  client/src/renderer/redux/actions/commands.test.js
  client/src/renderer/redux/reducers/commands.js
  client/src/renderer/redux/reducers/commands.test.js
  client/src/renderer/redux/reducers/shortcuts.js
Labels: size/L

#113 Parse the rest of the text-properties tag in ODT where possible
  server/src/parsers/odt/text.rs
Labels: size/M

#115 Minor ODT parser fixes
  server/src/document/meta.rs
  server/src/document/mod.rs
  server/src/document/node.rs
  server/src/parsers/odt/table.rs
Labels: size/XS

#116 Add support for parsing ODT page layout properties
  server/src/parsers/odt/mod.rs
  server/src/parsers/odt/styles.rs
  server/src/parsers/odt/text.rs
Labels: size/M

#118 Parse paragraph properties in ODT
  server/src/parsers/odt/mod.rs
  server/src/parsers/odt/styles.rs
  server/src/parsers/odt/text.rs
Labels: size/L

#121 Bring develop up to date with release v0.3.0
  client/package.json
  server/Cargo.toml
Labels: size/XS
