Repository sean0x42/kauri, pull requests merged in 2019-04, with the labels that each got.

#8 New Travis setup for the Electron-based version
  .travis.yml
  client/build.sh
  client/package.json
  server/build.sh
  server/src/main.rs
Labels: size/M

#6 Add Electron front-end
  .gitignore
  .hound.yml
  .jshintrc
  .scss-lint.yml
  .travis.yml
  client/.gitignore
  client/.prettierrc
  client/build.sh
  client/index.html
  client/main.js
  client/package.json
  client/src/app.jsx
  client/src/components/App/demo.json
  client/src/components/App/index.jsx
  client/src/components/App/styles.scss
  client/src/components/Editor/Heading.jsx
  client/src/components/Editor/Paragraph.jsx
  client/src/components/Editor/ToolBar/StyleSelector.jsx
  client/src/components/Editor/ToolBar/index.jsx
  client/src/components/Editor/ToolBar/styles.scss
  client/src/components/Editor/index.jsx
  client/src/components/Editor/styles.scss
  client/src/components/Header/index.jsx
  client/src/components/Header/styles.scss
  client/src/dom/RenderError.js
  client/src/dom/render.jsx
  client/src/styles/application.scss
  client/src/styles/elements/_body.scss
  client/src/util/ExtendableError.js
  client/webpack.config.js
  client/yarn.lock
  rustfmt.toml
  server/.gitignore
  server/Cargo.toml
  server/build.sh
  server/rustfmt.toml
  server/src/main.rs
  src/main.rs
Labels: enhancement, rendering, size/XXL

#9 Include js files in root when running `yarn clean`
  .github/PULL_REQUEST_TEMPLATE.md
  client/main.js
  client/package.json
Labels: size/XS
