Repository sean0x42/kauri, pull requests merged in 2019-05, with the labels that each got.

#10 OpenDocument Text parsing
  client/src/components/App/index.jsx
  client/src/components/Editor/index.jsx
  client/src/util/MenuConfigurator.js
  server/Cargo.toml
  server/src/main.rs
Labels: size/L

#12 Improve developer quality of life
  client/package.json
  client/src/main/index.js
  client/src/renderer/app.jsx
  client/src/renderer/components/App/demo.json
  client/src/renderer/components/App/index.jsx
  client/src/renderer/components/App/styles.scss
  client/src/renderer/components/Editor/Heading.jsx
  client/src/renderer/components/Editor/Paragraph.jsx
  client/src/renderer/components/Editor/ToolBar/StyleSelector.jsx
  client/src/renderer/components/Editor/ToolBar/index.jsx
  client/src/renderer/components/Editor/ToolBar/styles.scss
  client/src/renderer/components/Editor/index.jsx
  client/src/renderer/components/Editor/styles.scss
  client/src/renderer/components/Header/index.jsx
  client/src/renderer/components/Header/styles.scss
  client/src/renderer/dom/RenderError.js
  client/src/renderer/dom/render.jsx
  client/src/renderer/styles/application.scss
  client/src/renderer/styles/elements/_body.scss
  client/src/renderer/util/ExtendableError.js
  client/src/renderer/util/MenuConfigurator.js
  client/webpack.renderer.js
  client/yarn.lock
Labels: client

#11 Styling support
  client/package.json
  client/src/main/index.js
  client/src/renderer/components/App/demo.json
  client/src/renderer/components/App/index.jsx
  client/src/renderer/components/Editor/Heading.jsx
  client/src/renderer/components/Editor/Paragraph.jsx
  client/src/renderer/components/Editor/ToolBar/FontColorSelector.jsx
  client/src/renderer/components/Editor/ToolBar/FontSelector.jsx
  client/src/renderer/components/Editor/ToolBar/FontSizeSelector.jsx
  client/src/renderer/components/Editor/ToolBar/StyleButtons.jsx
  client/src/renderer/components/Editor/ToolBar/index.jsx
  client/src/renderer/components/Editor/ToolBar/styles.scss
  client/src/renderer/dom/render.jsx
  client/yarn.lock
  server/src/main.rs
Labels: client, daemon, size/XL

#16 Added basic document implementation
  .travis.yml
  server/Cargo.toml
  server/build.sh
  server/src/document/mod.rs
  server/src/document/node.rs
  server/src/document/units.rs
  server/src/main.rs
Labels: size/L

#19 Add Dependabot badge to README
  README.md
Labels: meta, size/XS

#21 Add Changelog
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: enhancement, meta, size/S

#15 Server/Daemon Refactoring
  client/src/renderer/components/App/demo.json
  client/src/renderer/components/App/index.jsx
  client/src/renderer/components/Editor/Heading.jsx
  client/src/renderer/components/Editor/Paragraph.jsx
  client/src/renderer/components/Editor/Span.jsx
  client/src/renderer/dom/render.jsx
  server/src/controllers/load.rs
  server/src/controllers/mod.rs
  server/src/controllers/util.rs
  server/src/document/mod.rs
  server/src/main.rs
  server/src/parsers/mod.rs
  server/src/parsers/odt.rs
  server/src/parsers/util.rs
Labels: size/XXL
