Repository sean0x42/kauri, pull requests merged in 2019-07, with the labels that each got.

#20 Add Clipboard
  client/package.json
  client/src/renderer/components/App/index.jsx
  client/src/renderer/components/App/styles.scss
  client/src/renderer/components/Clipboard/index.jsx
  client/src/renderer/components/Clipboard/styles.scss
  client/yarn.lock
Labels: client, clipboard, enhancement

#52 Table support
  CHANGELOG.md
  client/src/renderer/components/Editor/Table.jsx
  client/src/renderer/components/Editor/TableCaption.jsx
  client/src/renderer/components/Editor/TableCell.jsx
  client/src/renderer/components/Editor/TableColumn.jsx
  client/src/renderer/components/Editor/TableColumnGroup.jsx
  client/src/renderer/components/Editor/TableRow.jsx
  client/src/renderer/dom/render.jsx
  server/src/document/node.rs
  server/src/parsers/odt.rs
  server/src/parsers/odt/mod.rs
  server/src/parsers/odt/table.rs
  server/src/parsers/odt/text.rs
Labels: size/XXL

#73 Hyperlink support
  CHANGELOG.md
  client/src/renderer/components/Editor/Anchor.jsx
  client/src/renderer/dom/render.jsx
  server/src/parsers/odt/mod.rs
  server/src/parsers/odt/text.rs
Labels: size/L

#74 Add module docs to main.rs
  server/src/main.rs
Labels: daemon, documentation, rust, size/S
