Repository sean0x42/kauri, pull requests merged in 2019-08, with the labels that each got.

#75 Add KDF technical spec link to README
  README.md
Labels: documentation, meta, size/XS

#54 Setup Client Testing
  client/jest.config.js
  client/package.json
  client/webpack.renderer.additions.js
  client/yarn.lock
Labels: client, enhancement, javascript, testing

#80 Add Redux
  client/package.json
  client/src/renderer/app.jsx
  client/src/renderer/index.jsx
  client/src/renderer/redux/actionTypes.js
  client/src/renderer/redux/actions.js
  client/src/renderer/redux/reducers/index.js
  client/src/renderer/redux/selectors.js
  client/src/renderer/redux/store.js
  client/webpack.renderer.additions.js
  client/yarn.lock
Labels: client, javascript, size/XL

#83 Command actions and reducers
  client/package.json
  client/src/renderer/components/Clipboard/index.jsx
  client/src/renderer/redux/actionTypes.js
  client/src/renderer/redux/actions.js
  client/src/renderer/redux/reducers/command.js
  client/src/renderer/redux/reducers/index.js
Labels: size/M

#82 KDF (the new document format) server implementation
  server/src/document/meta.rs
  server/src/document/mod.rs
  server/src/document/node.rs
  server/src/document/styles.rs
Labels: KDF, size/M

#84 Refactor the ODT parser to use KDF
  server/src/document/mod.rs
  server/src/document/node.rs
  server/src/document/units.rs
  server/src/parsers/odt/mod.rs
  server/src/parsers/odt/table.rs
  server/src/parsers/odt/text.rs
Labels: size/L

#86 Release v0.2-alpha (for develop branch)
  CHANGELOG.md
  client/package.json
  server/Cargo.toml
Labels: size/S

#87 Add Redux developer tools
  client/package.json
  client/src/main/index.js
  client/src/renderer/redux/reducers/commands.js
  client/src/renderer/redux/reducers/index.js
  client/src/renderer/redux/store.js
Labels: client, javascript, size/M

#88 Remove redundant initial state in commands.js
  client/src/renderer/redux/reducers/commands.js
Labels: client, javascript, size/XS

#90 Create caret position
  client/src/renderer/components/Editor/index.jsx
  client/src/renderer/redux/actionTypes.js
  client/src/renderer/redux/actions.js
  client/src/renderer/redux/reducers/caretPosition.js
  client/src/renderer/redux/reducers/index.js
Labels: size/M

#91 Support for parsing named styles in ODT
  server/src/parsers/odt/mod.rs
  server/src/parsers/odt/styles.rs
  server/src/parsers/odt/table.rs
  server/src/parsers/odt/text.rs
Labels: size/XL

#93 Default outline level parsing support
  server/src/document/node.rs
  server/src/document/styles.rs
  server/src/parsers/odt/mod.rs
  server/src/parsers/odt/styles.rs
  server/src/parsers/odt/table.rs
  server/src/parsers/odt/text.rs
Labels: size/M

#92 Add tests for reducers
  client/.babelrc
  client/build.sh
  client/jest.config.js
  client/package.json
  client/src/renderer/components/Clipboard/index.jsx
  client/test/Redux/ActionCreator/commandActionTest.js
  client/test/Redux/Reducer/commandReducerTest.js
  client/webpack.renderer.additions.js
  client/yarn.lock
Labels: size/M

#94 Support for parsing metadata in ODT
  server/src/parsers/odt/meta.rs
  server/src/parsers/odt/mod.rs
Labels: size/L

#95 Improve Travis CI config (parallelize builds etc.)
  .travis.yml
  client/build.sh
  server/build.sh
Labels: ci, meta, size/M

#97 Feature metadata reducer
  client/src/renderer/redux/reducers/index.js
  client/src/renderer/redux/reducers/metadata.js
  client/src/renderer/redux/reducers/metadata.json
Labels: size/S

#98 Implement metadata reducer
  client/src/renderer/redux/actionTypes.js
  client/src/renderer/redux/actions.js
  client/src/renderer/redux/reducers/metadata.js
  client/src/renderer/redux/reducers/metadata.json
  client/test/redux/actions/metadata.test.js
  client/test/redux/reducers/metadata.test.js
Labels: size/L

#99 Server KDF implementation updates
  server/src/document/node.rs
  server/src/parsers/odt/mod.rs
Labels: size/L

#100 Feature move jest tests
  client/package.json
  client/src/renderer/redux/commands.test.js
  client/src/renderer/redux/metadata.test.js
  client/src/renderer/redux/reducers/commands.test.js
  client/src/renderer/redux/reducers/metadata.test.js
Labels: size/S

#103 Update Jest moduleDirectories
  client/jest.config.js
Labels: client, javascript, size/XS, testing

#102 Bump Preact to 10.0.0-rc.1 (new release candidate)
  client/package.json
  client/yarn.lock
Labels: size/S

#101 Feature document reducer
  client/src/renderer/redux/actionTypes.js
  client/src/renderer/redux/actions.js
  client/src/renderer/redux/actions/commands.js
  client/src/renderer/redux/actions/commands.test.js
  client/src/renderer/redux/actions/document.js
  client/src/renderer/redux/actions/document.test.js
  client/src/renderer/redux/actions/index.js
  client/src/renderer/redux/actions/metadata.js
  client/src/renderer/redux/actions/metadata.test.js
  client/src/renderer/redux/actions/types.js
  client/src/renderer/redux/reducers/caretPosition.js
  client/src/renderer/redux/reducers/commands.js
  client/src/renderer/redux/reducers/commands.test.js
  client/src/renderer/redux/reducers/document.js
  client/src/renderer/redux/reducers/index.js
  client/src/renderer/redux/reducers/metadata.js
  client/src/renderer/redux/reducers/metadata.test.js
Labels: size/L
