Repository sean0x42/kauri, pull requests merged in 2019-10, with the labels that each got.

#117 Render CSS styles to string
  client/package.json
  client/src/renderer/components/Editor/Elements/index.jsx
  client/src/renderer/components/Editor/index.jsx
  client/src/renderer/redux/actions/styles.js
  client/src/renderer/redux/actions/styles.test.js
  client/src/renderer/redux/reducers/styles.js
  client/src/renderer/redux/reducers/styles.json
  client/src/renderer/redux/reducers/styles.test.js
  client/src/renderer/render/style.js
  client/src/renderer/render/style.test.js
  client/src/renderer/render/style.ts
  client/yarn.lock
Labels: size/L

#122 Bump Preact to 10.0.0 (X)
  client/package.json
  client/yarn.lock
Labels: size/S

#123 Feature keyboard shortcut
  client/jest.config.js
  client/src/renderer/commands/index.js
  client/src/renderer/commands/keybinds.json
  client/src/renderer/commands/shortcuts.js
  client/src/renderer/commands/shortcuts.test.js
  client/src/renderer/components/Clipboard/index.jsx
  client/src/renderer/components/ShortcutListener.js
  client/src/renderer/helpers/uniqueIdGen.js
  client/src/renderer/redux/actions/commands.js
  client/src/renderer/redux/actions/commands.test.js
  client/src/renderer/redux/actions/shortcuts.js
  client/src/renderer/redux/actions/types.ts
  client/src/renderer/redux/reducers/commands.js
  client/src/renderer/redux/reducers/commands.test.js
  client/src/renderer/redux/reducers/shortcuts.js
  client/src/renderer/redux/reducers/shortcuts.test.js
Labels: size/L

#124 Feature selection updater
  client/src/renderer/commands/index.js
  client/src/renderer/commands/shortcuts.js
  client/src/renderer/components/Editor/Nodes/index.jsx
  client/src/renderer/components/Editor/index.jsx
  client/src/renderer/components/ShortcutListener.js
  client/src/renderer/redux/actions/document.js
  client/src/renderer/redux/actions/document.test.js
  client/src/renderer/redux/actions/types.ts
  client/src/renderer/redux/reducers/document.js
Labels: size/L

#125 Support for loading and saving KDF (server side)
  server/src/controllers/load.rs
  server/src/controllers/mod.rs
  server/src/controllers/save/mod.rs
  server/src/controllers/save/transport.rs
  server/src/controllers/util.rs
  server/src/document/node.rs
  server/src/main.rs
  server/src/parsers/kdf.rs
  server/src/parsers/mod.rs
  server/src/savers/kdf.rs
  server/src/savers/mod.rs
Labels: size/L

#127 Updates for server compliance with KDF spec
  server/src/document/meta.rs
  server/src/document/node.rs
  server/src/parsers/odt/meta.rs
  server/src/parsers/odt/mod.rs
Labels: size/M

#128 helmet no longer steals editor focus
  client/src/renderer/components/Editor/index.jsx
Labels: size/S

#129 Fix issue where current page was not rendered
  client/src/renderer/redux/actions/document.test.js
  client/src/renderer/redux/reducers/styles.js
  client/src/renderer/render/content.tsx
Labels: size/S

#126 Add save to KDF
  client/package.json
  client/src/renderer/helpers/document.js
  client/src/renderer/helpers/menu.js
  client/src/renderer/helpers/translateKDF.test.js
  client/src/renderer/redux/reducers/metadata.js
  client/src/renderer/redux/reducers/pageStyles.js
  client/src/renderer/redux/reducers/pageStyles.test.js
  client/src/renderer/redux/reducers/styles.js
  client/src/renderer/redux/store.js
  client/yarn.lock
  server/src/document/node.rs
Labels: size/L

#130 Set cursor position on rerender
  client/src/renderer/components/Editor/index.jsx
  client/src/renderer/redux/actions/document.js
  client/src/renderer/redux/actions/types.ts
  client/src/renderer/redux/reducers/cache.js
  client/src/renderer/redux/reducers/document.js
Labels: size/M
